version: '3.2'

services:
  db:
    image: postgres:12.3
    container_name: go_marketer
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=go_marketer_development
    ports:
      - "5432:5432"
